### PR TITLE
remount-sysroot: only remount on OSTree systems

### PR DESCRIPTION
**Pull request by jlebon**

### CODE REVIEW

**Comment by dustymabe** [comment]
so we do need the first part of this unit on classic systems

```
ExecStart=/bin/mount -o remount,rw /sysroot
```

but not the 2nd part

```
ExecStart=/bin/mount -o remount,rw /sysroot/var
```

**Comment by cgwalters** [comment]
i think systemd will evaluate the conditions pretty early though, not after each unit right?

**Comment by jlebon** [comment]
Are you testing this on a classic cloud F28 image?

**Comment by dustymabe** [comment]
> Are you testing this on a classic cloud F28 image?

yes
https://github.com/dustymabe/bootengine/blob/1f80d41f692adf54e8433b588e94e6caeb3153da/dracut/README.txt#L2-L7

**Comment by jlebon** [comment]
OK, updated the PR! :arrow_up: 
Tested on both classic and OSTree systems.

**Comment by jlebon** [comment]
> i think systemd will evaluate the conditions pretty early though, not after each unit right?

It turns out that it evaluates the conditions right before start up. See: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=:

> The condition is checked at the time the queued start job is to be executed.

**Comment by dustymabe** [comment]
LGTM

**Pull request merged**
